apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etcd
      suite: pachyderm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: etcd
        suite: pachyderm
      name: etcd
      namespace: pachyderm
    spec:
      containers:
      - command:
        - /usr/local/bin/etcd
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://0.0.0.0:2379
        - --data-dir=/var/data/etcd
        - --auto-compaction-retention=1
        - --max-txn-ops=10000
        - --max-request-bytes=52428800
        - --quota-backend-bytes=8589934592
        image: pachyderm/etcd:v3.3.5
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          name: client-port
          protocol: TCP
        - containerPort: 2380
          name: peer-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512M
          requests:
            cpu: 250m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/data/etcd
          name: etcd-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/pachyderm/etcd
          type: DirectoryOrCreate
        name: etcd-storage
