apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    suite: pachyderm
  name: pachyderm-worker
  namespace: pachyderm
rules:
- resources:
  - services
  verbs:
  - get
  - list
  - update
  - create
  - delete
