apiVersion: v1
kind: Service
metadata:
  name: {{ include "pach_chart.fullname" . }}
  labels:
    {{- include "pach_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      - name: dash-http
        nodePort: 30080
        port: 8080
      - name: grpc-proxy-http
        nodePort: 30081
        port: 8081
  selector:
        app: dash
        suite: pachyderm
