apiVersion: v1
kind: Service
metadata:
  name: {{ include "pach_chart.fullname" . }}
  labels:
    {{- include "pach_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client-port
      nodePort: 32379
      port: 2379
  selector:
    app: etcd
  type: NodePort
