apiVersion: v1
kind: Service
metadata:
  name: {{ include "pach_chart.fullname" . }}
  labels:
    {{- include "pach_chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api-grpc-peer-port
      port: 30653
      targetPort: 653
  selector:
    app: pachd
