apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
  namespace: pachyderm
spec:
  clusterIP: 10.96.195.144
  ports:
  - name: dash-http
    nodePort: 30080
    port: 8080
  - name: grpc-proxy-http
    nodePort: 30081
    port: 8081
  selector:
    app: dash
    suite: pachyderm
  type: NodePort
