apiVersion: v1
kind: Service
metadata:
  labels:
    app: pachd
    suite: pachyderm
  name: pachd-peer
  namespace: pachyderm
spec:
  clusterIP: 10.110.107.120
  ports:
  - name: api-grpc-peer-port
    port: 30653
    targetPort: 653
  selector:
    app: pachd
