apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    suite: pachyderm
  name: etcd
  namespace: pachyderm
spec:
  clusterIP: 10.103.215.108
  ports:
  - name: client-port
    nodePort: 32379
    port: 2379
  selector:
    app: etcd
  type: NodePort
