apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "656"
    prometheus.io/scrape: "true"
  labels:
    app: pachd
    suite: pachyderm
  name: pachd
  namespace: pachyderm
spec:
  clusterIP: 10.100.194.188
  ports:
  - name: api-grpc-port
    nodePort: 30650
    port: 650
  - name: trace-port
    nodePort: 30651
    port: 651
  - name: api-http-port
    nodePort: 30652
    port: 652
  - name: saml-port
    nodePort: 30654
    port: 654
  - name: oidc-port
    nodePort: 30657
    port: 657
  - name: api-git-port
    nodePort: 30655
    port: 655
  - name: s3gateway-port
    nodePort: 30600
    port: 600
  selector:
    app: pachd
  type: NodePort
