apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    suite: pachyderm
  name: pachyderm-worker
  namespace: pachyderm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pachyderm-worker
subjects:
- kind: ServiceAccount
  name: pachyderm-worker
  namespace: pachyderm
